PROBLEM 1: NORMALIZATION PROBLEM

In [1]:
import numpy as np

In [13]:
#Create a 5x5 array

X = np.random.rand(5, 5)
print("Original Array X:")
print(X)

Original Array X:
[[0.70020741 0.02793172 0.50197027 0.84207143 0.03579843]
 [0.9291276  0.59851951 0.85091472 0.67592551 0.92925843]
 [0.21202938 0.09490702 0.24088882 0.60310659 0.82338665]
 [0.78243029 0.65737754 0.8725034  0.30238185 0.0823218 ]
 [0.57912978 0.67982122 0.64128318 0.09187167 0.72900689]]


In [3]:
#Calculate the mean and standard deviation

mean = X.mean()
std = X.std()
print("Mean: ", mean)
print("Standard Deviation: ", std)

Mean:  0.5167406339285227
Standard Deviation:  0.2979187735764119


In [14]:
#Normalize the array using the formula

X_normalized = (X - mean) / std
print("Normalized Array:")
print(X_normalized)

Normalized Array:
[[ 0.61582817 -1.64074558 -0.04957851  1.09201172 -1.61434005]
 [ 1.38422619  0.27450058  1.12169529  0.53432309  1.38466532]
 [-1.02279977 -1.41593498 -0.9259296   0.28989766  1.02929402]
 [ 0.89181911  0.47206459  1.19416029 -0.71952091 -1.45817877]
 [ 0.20941662  0.54739949  0.41804197 -1.42612352  0.71249708]]


In [7]:
#Save the normalized array to a .npy file

np.save("X_normalized.npy", X_normalized)

In [15]:
# Load back to the file to confirm if it was saved 

loaded_array = np.load("X_normalized.npy")
print("Loaded Normalized Array:")
print(loaded_array)

Loaded Normalized Array:
[[-0.32037243 -1.39046613 -1.09642214  1.52280003 -0.98395064]
 [ 0.51167473 -1.44937798  1.02502841 -1.39400174  0.0794821 ]
 [ 1.48998307 -1.41988685  0.85097228  0.49555445  1.09738007]
 [ 0.88204591 -0.48653732  0.49635297 -0.56300203  0.36069099]
 [-0.21729213 -0.79237309  1.47976635 -1.11691247  0.93886358]]


Problem 2: DIVISIBLE BY 3

In [16]:
import numpy as np

In [17]:
# Create a 10x10 ndarray with the squares of the first 100 positive int

A = np.arange(1, 101) ** 2 # squares of numbers 1-100
A = A.reshape(10, 10)      # reshape into a 10x10 array

In [19]:
print("10x10 Array A:")
print(A)

10x10 Array A:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [20]:
# Find all elements divisible by 3

div_by_3 = A[A % 3 == 0]

In [21]:
print("Elements Divisible by 3:")
print(div_by_3)

Elements Divisible by 3:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [22]:
# Save the result into a .npy file

np.save("div_by_3.npy", div_by_3)

In [23]:
# load back the file to verify

loaded = np.load("div_by_3.npy")

In [24]:
print("Loaded Elements Divisible by 3:")
print(loaded)

Loaded Elements Divisible by 3:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
